[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }

tokio = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1.83"
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
tracing = { workspace = true }
validator = { workspace = true }
